kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: demoservice1
spec:
  ports:
    - name: nginx      
      port: 3002                             # Containers port exposed
      targetPort: 80

    - name: sampleapp
      port: 3003
      targetPort: 3000     

  selector:
    name: deployment1                    # Apply this service to any pods which has the specific label
  type: NodePort                       # Specifies the service type i.e ClusterIP or NodePort

