kind: Deployment
apiVersion: apps/v1
metadata:
   name: updated-deployment-1


spec:
  replicas: 2
  selector:
    matchLabels:
      name: deployment1
  template:
    metadata:
       name: testpod
       labels:
         name: deployment1
    spec:
      containers:

#        - name: cont1
#          image: kevalp566/getting-started
#          ports:
#            - containerPort: 3000
#          volumeMounts:
#            - name: app-data
#              mountPath: "/opt/data"

        - name: cont2
          image: ubuntu
          command: ["/bin/bash","-c", "while true; do echo Hello; sleep 5; done"]
          volumeMounts:
            - name: app-data
              mountPath: "/opt/data"

        - name: cont3
          image: centos
          command: ["/bin/bash","-c", "while true; do echo Hello; sleep 5; done"]
          volumeMounts:
            - name: app-data
              mountPath: "/opt/cont3/data"


#        - name: msg2
#          image: nginx
#          ports:
#            - containerPort: 80
      
      volumes:
        - name: app-data
          emptyDir: {}
